### ISSUE TITLE
Datadog Log Shipper failing 

### ISSUE THREAD

**Issue by djtecha** [jenkinsci/datadog-plugin#182] opened 2021-02-12 22:02 UTC
Hello all, running the latest JENKINS and Datadog and the logging used to work shipping to a datadog agent running on the cluster. Now I just get this:
```
Feb 12, 2021 12:54:21 AM org.jenkinsci.plugins.workflow.log.TaskListenerDecorator$DecoratedTaskListener getLogger
WARNING: null
java.lang.NullPointerException
at org.datadog.jenkins.plugins.datadog.logs.DatadogTaskListenerDecorator.decorate(DatadogTaskListenerDecorator.java:53)
at org.jenkinsci.plugins.workflow.log.TaskListenerDecorator$DecoratedTaskListener.getLogger(TaskListenerDecorator.java:237)
at org.jenkinsci.plugins.workflow.log.TaskListenerDecorator$CloseableTaskListener.getLogger(TaskListenerDecorator.java:279)
at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1381)
at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1333)
at hudson.remoting.UserRequest.perform(UserRequest.java:211)
at hudson.remoting.UserRequest.perform(UserRequest.java:54)
at hudson.remoting.Request$2.run(Request.java:376)
at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:119)
at java.lang.Thread.run(Thread.java:748)
```
datadog helm chart version: 2.8.3
jenkins helm chart version: 3.1.8

datadog plugin 2.8.1

**Comment by FlorianVeaux** [comment] 2021-02-15 08:57
Hey @djtecha, thanks for raising the issue it seems a bit concerning indeed.
Can you share more details about your previous setup when logging was working? In particular which combination of the versions of jenkins and the datadog plugin was previously working?

Based on that traceback, it looks like the error seems to come from a (jenkins) master to agent call. Our class `TaskListenerDecorator` gets serialized and transferred to the agent jvm and something. But that wouldn't be "new" that's why I'm curious about your previous setup.

**Comment by djtecha** [comment] 2021-02-15 17:13
Sure I was running the 
datadog agent helm chart 2.6.15
datadog jenkins plugin 2.4.0
jenkins helm chart 3.0.14

I had to upgrade the datadog chart to allow for multiple host ports so I could sent both metrics and logs to the DSD controller. I have also confirmed from the jenkins pod that it can hit the datadog integration listening on the agent pod.

**Comment by FlorianVeaux** [comment] 2021-02-17 10:07
Thanks for the details, unfortunately I can't reproduce. Do you have simple reproduction steps?
Additionally what I'm mostly looking for is the exact version (either of the datadog-plugin or of jenkins) that introduced this regression. I'm not sure today if that comes up because of a change we made, or a jenkins change we didn't account for.

That being said, based on the traceback you shared and information I can find, there would be a way to update the `DatadogTaskListenerDecorator` class to make it completely serializable. I believe this should fix your issue, but I can't tell why this error does not occur with other versions of the plugin as it isn't new.

**Comment by coignetp** [comment] 2021-03-16 16:03
Hi @djtecha , thanks for raising this issue.
#188 proposes a fix, could you try it and see if it works on your side? I'm linking the `datadog.hpi` file in a zip (`.hpi` are not supported by github).
[datadog.hpi.zip](https://github.com/jenkinsci/datadog-plugin/files/6150466/datadog.hpi.zip)

**Comment by djtecha** [comment] 2021-03-16 22:57
Hey, its working again :)

**Closed** 2021-03-17 08:45 UTC
Labels: kind/bug
