### ISSUE TITLE
Jenkins Datadog plugin - Log Collection Port Error

### ISSUE THREAD

**Issue by vvalderrv** [jenkinsci/datadog-plugin#272] opened 2022-01-12 20:52 UTC
The Datadog Agent configuration of the Jenkins Datadog Plugin shows the Log Collection Port (Optional). If no port is configured for Log Collection and you click Test connection, you get an error "The port cannot be empty."

1. Go to Manage Jenkins
2. Click on Configure System
3. Scroll down to Datadog Plugin
4. Click on  Use the Datadog Agent to report to Datadog (recommended)
5. Configuration

- Agent Host: localhost
-  DogStatsD Port: 8125
- Log Collection Port: empty

6. Click Test connection
7. Error: "The port cannot be empty"

**Expected behavior**
The Log Collection Port should not be a required field. The test should test the DogStatsD Port and display the result.

**Screenshots**
Screenshot available if needed

**Environment and Versions (please complete the following information):**
This occurs on multiple Jenkins instances

Jenkins
Jenkins 2.303.3 with Datadog plugin 3.3.0
Jenkins 2.289.2 with Datadog plugin 3.4.1
Jenkins 2.303.1 with Datadog plugin 3.1.0

**Comment by yzhan289** [comment] 2022-01-25 17:51
Hi 👋 , thanks for raising this. To help with fixing this bug, do you have log collection enabled?

**Comment by yzhan289** [comment] 2022-01-26 14:18
Hi, I talked with the team to learn more about the functionality of `Test connection`. They reported that the `Test connection` button is related to only the `Log Collection Port`. The `DogStatsD port` cannot be tested because it's a UDP port.

**Comment by yzhan289** [comment] 2022-01-27 22:49
PR making the buttons for `Test connection` more clear was just merged. I'll close this ticket since the intended behavior was occurring correctly, although the button may have been misleading.

**Closed by yzhan289** 2022-01-27 22:49 UTC
Labels: kind/bug
