### ISSUE TITLE
All classic jobs in jenkins turn into failed on datadog plugin v6.0.0

### ISSUE THREAD

**Issue by bitle** [jenkinsci/datadog-plugin#393] opened 2024-02-03 08:32 UTC
**Describe the bug**
Today I upgraded all plugins in jenkins to the latest version. Among them is the most recent version of Datadog Plugin.
After jenkins restarted all Successful builds of classic jobs show up as failed. I can still see in the logs that the result was SUCCESS.
Here's what I found in the logs:
```
ConversionException: 
---- Debugging information ---- cause-exception : java.lang.NumberFormatException cause-message : For input string: "https://jenkins2.dev.lockhart.io/job/Infrastructure/job/fmc/job/cdfmc_rds_deploy/job/deploy_fmc_with_rds/2750/" class :
 java.lang.Long required-type : java.lang.Long converter-type : com.thoughtworks.xstream.converters.SingleValueConverterWrapper wrapped-converter : com.thoughtworks.xstream.converters.basic.LongConverter path : /build/actions/org.datadog.jenkins.plugins.datadog.traces.BuildSpanAction/buildData/buildUrl line number : 137 class[1] : org.datadog.jenkins.plugins.datadog.traces.message.TraceSpan$TraceSpanContext required-type[1] : org.datadog.jenkins.plugins.datadog.traces.message.TraceSpan$TraceSpanContext converter-type[1] : hudson.util.XStream2$AssociatedConverterImpl class[2] : org.datadog.jenkins.plugins.datadog.traces.BuildSpanAction required-type[2] : org.datadog.jenkins.plugins.datadog.traces.BuildSpanAction -------------------------------, CannotResolveClassException: buildParameters, CannotResolveClassException: charsetName, CannotResolveClassException: nodeName, CannotResolveClassException: jobName, CannotResolveClassException: baseJobName, CannotResolveClassException: buildTag, CannotResolveClassException: jenkinsUrl, CannotResolveClassException: executorNumber, CannotResolveClassException: javaHome, CannotResolveClassException: branch, CannotResolveClassException: gitUrl, CannotResolveClassException: gitCommit, CannotResolveClassException: isCompleted, CannotResolveClassException: hostname, CannotResolveClassException: userId, CannotResolveClassException: tags, CannotResolveClassException: startTime, CannotResolveClassException: endTime, ConversionException: Refusing to unmarshal duration for security reasons; see https://www.jenkins.io/redirect/class-filter/ ---- Debugging information ---- message : Refusing to unmarshal duration for security reasons; see https://www.jenkins.io/redirect/class-filter/ class : java.time.Duration required-type : java.time.Duration converter-type : hudson.util.XStream2$BlacklistedTypesConverter path : /build/actions/org.datadog.jenkins.plugins.datadog.traces.BuildSpanAction/buildData/duration line number : 197 -------------------------------, CannotResolveClassException: millisInQueue, CannotResolveClassException: buildSpanContext
```

I reverted back to the previous version and it fixed my issues.

**To Reproduce**
I didn't try to reproduce this issue. I can provide my job configs and build history if needed.

**Expected behavior**

**Screenshots**
![Screenshot 2024-02-03 at 9 30 33 AM](https://github.com/jenkinsci/datadog-plugin/assets/285793/44cf9bf1-5554-4f63-81f3-0a84e5f63489)

**Environment and Versions (please complete the following information):**
Jenkins 2.426.3
Datadog 5.6.2 -> 6.0.0

**Additional context**

**Comment by jeohist** [comment] 2024-02-06 15:12
We experienced the same issue, but unfortunately reverting to the old version did not resolve our issues.

**Comment by nikita-tkachenko-datadog** [comment] 2024-02-06 16:03
@bitle, @jeohist, thank you for reporting this. The issue was resolve in release v6.0.1. Please try updating and let me know if the issue persists. Thank you!

**Comment by lemeurherve** [comment] 2024-02-07 19:22
@nikita-tkachenko-datadog we upgraded from 6.0.0 to 6.0.1 after the stackoverflow this afternoon, but unfortunately all previous jobs are still marked as "failed" in 1970.

Ex: https://ci.jenkins.io/job/Infra/job/pipeline-library/job/master/ (previous builds have successfully finished while they appear failed)

<img width="256" alt="image" src="https://github.com/jenkinsci/datadog-plugin/assets/91831478/d0c0d2aa-93ce-41bc-bab3-9955d10f9c5b">

**Comment by nikita-tkachenko-datadog** [comment] 2024-02-07 19:32
Hi @lemeurherve,

Could you please provide some additional info?
- do you see any exceptions/error messages in the Jenkins log, in the Datadog plugin log, or in the Manage Old Data screen? If yes, could you please share them? 
- would it be possible for you to provide an example of a `build.xml` of a job that is displayed incorrectly? I believe they're stored at `$JENKINS_HOME/jobs/<JOB_NAME>/builds/<BUILD_NUMBER>/build.xml`. If the entire file cannot be provided because it contains sensitive info, providing a part of it would be helpful as well.

Thank you!

**Comment by lemeurherve** [comment] 2024-02-07 19:35
I'll provide you these elements first thing in the morning tomorrow.

**Comment by nikita-tkachenko-datadog** [comment] 2024-02-07 21:10
As a side note, https://issues.jenkins.io/browse/JENKINS-66328 describes a similar issue.
Some of the reports in there are from 25/01/202 (which is before Datadog plugin v6.0.0 was released) and the reporters claim that they're not using the Datadog plugin.

So while there is a plugin data deserialisation problem in v6.0.0, it is possible that the date/status display issue is caused by something else.

**Comment by dduportal** [comment] 2024-02-08 07:40
> or in the Manage Old Data screen? If yes, could you please share them?

First (quick) feedback on ci.jenkins.io (I'll let @lemeurherve provides more details with logs and/or `build.xml` excerpts) : after upgrading `datadog` from 6.0.0 to 6.0.1, we had the following warning in the "Manage Old Data" screen:

<img width="1520" alt="Capture d’écran 2024-02-07 à 16 03 22" src="https://github.com/jenkinsci/datadog-plugin/assets/1522731/3e0bc811-1dce-4864-b8d0-da1d56b81dc6">

**Closed** 2024-02-13 11:24 UTC
Labels: kind/bug
